package main

import "time"

func init() {
	rootCmd.PersistentFlags().StringVar(&globalWorkspace, "workspace", ".", "Workspace root (default: current directory)")
	rootCmd.PersistentFlags().StringVar(&globalMux, "mux", "", "Terminal multiplexer backend: tmux or herdr (default: recorded runtime, then tmux)")

	initCmd.Flags().BoolVar(&initSkipDefaultPack, "skip-default-pack", false, "Create the base workspace without installing the default pack")
	initCmd.Flags().BoolVar(&initDryRun, "dry-run", false, "Print what would be created without writing files")
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing generated files")
	packInspectCmd.Flags().BoolVar(&packInspectJSON, "json", false, "Output as JSON")

	doctorCmd.Flags().BoolVar(&doctorFix, "fix", false, "Remove provably-stale state locks (dead PID or old without a valid PID); live locks are never touched")
	doctorCmd.Flags().BoolVar(&doctorSystem, "system", false, "Check Orc install readiness outside a workspace")
	hooksInstallCmd.Flags().BoolVar(&hooksInstallDryRun, "dry-run", false, "Preview hook installation without writing")
	nextCmd.Flags().BoolVar(&nextJSON, "json", false, "Output as JSON")
	nextCmd.Flags().BoolVar(&nextDry, "dry", false, "Print the launch command without executing it")
	nextCmd.Flags().StringVar(&nextWorker, "worker", "", "Override the workflow's default worker (worker ID)")
	statusCmd.Flags().BoolVar(&statusJSON, "json", false, "Output as JSON")
	statusCmd.Flags().StringArrayVar(&statusLabels, "label", nil, "Only show features carrying this label, as key or key=value; repeat to require several")
	sessionsCmd.Flags().BoolVar(&sessionsJSON, "json", false, "Output as JSON")
	sessionsCmd.Flags().StringArrayVar(&sessionsLabels, "label", nil, "Only show sessions whose feature carries this label, as key or key=value")
	sessionsCmd.Flags().BoolVar(&sessionsAll, "all", false, "Include recent provider sessions not managed by Orc")
	sessionsResumeCmd.Flags().StringVar(&sessionsResumeEngine, "engine", "", "Provider engine when the session ID is ambiguous: claude or codex")
	sessionsResumeCmd.Flags().StringVar(&sessionsResumeCWD, "cwd", "", "Override the recorded working directory")
	sessionsResumeCmd.Flags().BoolVar(&sessionsResumeDry, "dry", false, "Print the exact resume command without running it")
	sessionsResumeCmd.Flags().BoolVar(&sessionsResumeForce, "force", false, "Resume even when provider metadata reports the session is active")
	sessionsParkCmd.Flags().BoolVar(&sessionsParkDry, "dry", false, "Preview resumable sessions without writing a snapshot or stopping tmux")
	sessionsParkCmd.Flags().BoolVar(&sessionsParkYes, "yes", false, "Confirm writing the snapshot and stopping the listed tmux sessions")
	sessionsUnparkCmd.Flags().BoolVar(&sessionsUnparkDry, "dry", false, "Preview the saved snapshot without creating tmux sessions")
	sessionsUnparkCmd.Flags().BoolVar(&sessionsUnparkYes, "yes", false, "Confirm recreating the listed tmux sessions")
	reportCmd.Flags().BoolVar(&reportJSON, "json", false, "Output as JSON")
	reportCmd.Flags().BoolVar(&reportArchived, "archived", false, "Include archived tickets in the aggregate (no-arg) report")
	artifactsCmd.Flags().BoolVar(&artifactsAll, "all", false, "Check every required artifact in the ticket workflow")
	artifactsCmd.Flags().BoolVar(&artifactsJSON, "json", false, "Output as JSON")
	workCmd.Flags().StringVar(&workSlug, "slug", "", "Optional slug suffix (e.g. add-user-export → TICKET-123-add-user-export)")
	workCmd.Flags().BoolVar(&workTmux, "tmux", false, "Enable tmux session for this ticket — session created automatically on first orc next")
	workCmd.Flags().BoolVar(&workNext, "next", false, "Immediately launch the first stage after creating the feature")
	workCmd.Flags().StringVar(&workWorkflow, "workflow", "", "Workflow to use (default: settings.default_workflow in orc.yaml)")
	markCmd.Flags().StringVar(&markWorker, "worker", "", "Worker ID that owns the new stage (next only)")
	markCmd.Flags().StringVar(&markResult, "result", "", "Summary of what was accomplished (next/done only)")
	markCmd.Flags().StringVar(&markStage, "stage", "", "New stage name (next only — required when crossing workflow boundaries)")
	markCmd.Flags().BoolVar(&markConfirm, "confirm", false, "Pause asking a yes/no question (pause only)")
	markCmd.Flags().BoolVar(&markText, "text", false, "Pause asking for a free-text answer (pause only)")
	markCmd.Flags().StringArrayVar(&markChoices, "choice", nil, "Pause asking to pick one option, as key=label; repeat for each choice (pause only)")
	markCmd.Flags().BoolVar(&markForce, "force", false, "Human override: advance past artifact_policy=block even when required artifacts are not ready (next only, recorded in history)")
	jitCmd.Flags().StringVar(&jitWorker, "worker", "", "Worker ID to run the task (required)")
	_ = jitCmd.MarkFlagRequired("worker")
	labelCmd.Flags().StringArrayVar(&labelRemove, "remove", nil, "Remove a label by key; repeat for several")
	jitCmd.Flags().BoolVar(&jitDry, "dry", false, "Print resolved worker and prompt without launching")
	jitCmd.Flags().BoolVar(&jitTmux, "tmux", false, "Send to the ticket's existing tmux session instead of foreground")
	watchCmd.Flags().StringVar(&watchInterval, "interval", "5s", "Refresh interval")
	watchCmd.Flags().BoolVar(&watchWide, "wide", false, "Render the wider table layout")
	watchCmd.Flags().BoolVar(&watchDemo, "demo", false, "Preview watch with synthetic workflow, state, and context data")
	railCmd.PersistentFlags().StringVar(&railLayout, "layout", "right", "Rail split layout: right or bottom")
	railCmd.PersistentFlags().StringVar(&railSize, "size", "", "Expanded rail size in columns or rows (default: 64; expand restores the prior size)")
	ctlAgentStateCmd.Flags().StringVar(&ctlStateTicket, "ticket", "", "Ticket whose exact recorded agent should be observed")
	_ = ctlAgentStateCmd.MarkFlagRequired("ticket")
	ctlAgentWatchCmd.Flags().StringVar(&ctlWatchTicket, "ticket", "", "Only stream the exact recorded agent for this ticket")
	ctlAgentWatchCmd.Flags().DurationVar(&ctlWatchInterval, "interval", time.Second, "Lifecycle polling interval")
	ctlAgentPromptCmd.Flags().StringVar(&ctlPromptTicket, "ticket", "", "Ticket whose exact recorded agent should receive the prompt")
	_ = ctlAgentPromptCmd.MarkFlagRequired("ticket")
	ctlAgentPromptCmd.Flags().BoolVar(&ctlPromptWait, "wait", false, "Wait for recognized lifecycle state after submitting")
	ctlAgentPromptCmd.Flags().StringArrayVar(&ctlPromptUntil, "until", nil, "Lifecycle state to wait for; repeat for multiple states")
	ctlAgentPromptCmd.Flags().DurationVar(&ctlPromptTimeout, "timeout", 2*time.Minute, "Maximum wait duration")
	ctlAgentWaitCmd.Flags().StringVar(&ctlWaitTicket, "ticket", "", "Ticket whose exact recorded agent should be observed")
	_ = ctlAgentWaitCmd.MarkFlagRequired("ticket")
	ctlAgentWaitCmd.Flags().StringArrayVar(&ctlWaitUntil, "until", nil, "Lifecycle state to wait for; repeat for multiple states")
	ctlAgentWaitCmd.Flags().DurationVar(&ctlWaitTimeout, "timeout", 2*time.Minute, "Maximum wait duration")
	ctlSessionCaptureCmd.Flags().StringVar(&ctlCaptureTicket, "ticket", "", "Ticket whose exact recorded agent pane should be captured")
	_ = ctlSessionCaptureCmd.MarkFlagRequired("ticket")
	ctlSessionCaptureCmd.Flags().IntVar(&ctlCaptureLines, "lines", 80, "Number of recent terminal lines to capture")

	nextCmd.ValidArgsFunction = ticketCompleter([]string{"pending", "active", "paused"}, false)
	statusCmd.ValidArgsFunction = ticketCompleter(nil, true)
	reportCmd.ValidArgsFunction = ticketCompleter(nil, true)
	artifactsCmd.ValidArgsFunction = ticketCompleter(nil, true)
	markCmd.ValidArgsFunction = ticketCompleter([]string{"pending", "active", "paused"}, false)
	answerCmd.ValidArgsFunction = ticketCompleter([]string{"paused"}, false)
	labelCmd.ValidArgsFunction = ticketCompleter(nil, true)
	attachCmd.ValidArgsFunction = ticketCompleter([]string{"active"}, false)
	archiveCmd.ValidArgsFunction = ticketCompleter([]string{"done"}, false)
	deleteCmd.ValidArgsFunction = ticketCompleter([]string{"done", "archived"}, true)
	jitCmd.ValidArgsFunction = ticketCompleter(nil, true)
	doctorCmd.ValidArgsFunction = ticketCompleter(nil, false)
	watchCmd.ValidArgsFunction = ticketCompleter(nil, false)

	agentEventCmd.Flags().StringVar(&agentEventAgentID, "agent-id", "", "Orc agent identity inherited by the provider")
	agentEventCmd.Flags().StringVar(&agentEventInstance, "instance", "", "Orc live instance identity inherited by the provider")
	agentEventCmd.Flags().StringVar(&agentEventEngine, "engine", "", "Provider engine reporting the event")
	agentEventCmd.Flags().StringVar(&agentEventProvider, "provider-session", "", "Provider-native session identity when available")
	agentEventCmd.Flags().StringVar(&agentEventLifecycle, "state", "", "Recognized lifecycle state")
	agentEventCmd.Flags().StringVar(&agentEventID, "event-id", "", "Provider event identity used for deduplication")
	_ = agentEventCmd.MarkFlagRequired("agent-id")
	_ = agentEventCmd.MarkFlagRequired("instance")
	_ = agentEventCmd.MarkFlagRequired("engine")
	_ = agentEventCmd.MarkFlagRequired("state")
	_ = agentEventCmd.MarkFlagRequired("event-id")

	packCmd.AddCommand(packListCmd)
	packCmd.AddCommand(packAvailableCmd)
	packCmd.AddCommand(packShowCmd)
	packCmd.AddCommand(packInspectCmd)
	packCmd.AddCommand(packInstallCmd)

	rootCmd.AddCommand(initCmd)
	rootCmd.AddCommand(packCmd)
	rootCmd.AddCommand(doctorCmd)
	hooksCmd.AddCommand(hooksInstallCmd)
	rootCmd.AddCommand(hooksCmd)
	rootCmd.AddCommand(nextCmd)
	rootCmd.AddCommand(statusCmd)
	sessionsCmd.AddCommand(sessionsResumeCmd)
	sessionsCmd.AddCommand(sessionsParkCmd)
	sessionsCmd.AddCommand(sessionsUnparkCmd)
	rootCmd.AddCommand(sessionsCmd)
	rootCmd.AddCommand(reportCmd)
	rootCmd.AddCommand(artifactsCmd)
	rootCmd.AddCommand(workCmd)
	rootCmd.AddCommand(markCmd)
	rootCmd.AddCommand(answerCmd)
	rootCmd.AddCommand(labelCmd)
	rootCmd.AddCommand(archiveCmd)
	rootCmd.AddCommand(deleteCmd)
	rootCmd.AddCommand(jitCmd)
	rootCmd.AddCommand(attachCmd)
	rootCmd.AddCommand(focusCmd)
	rootCmd.AddCommand(dashboardCmd)
	rootCmd.AddCommand(watchCmd)
	railCmd.AddCommand(railOpenCmd, railCloseCmd, railToggleCmd, railCollapseCmd, railExpandCmd, railToggleCollapsedCmd)
	rootCmd.AddCommand(railCmd)
	rootCmd.AddCommand(agentEventCmd)
	ctlCmd.AddCommand(ctlStatusCmd)
	ctlAgentCmd.AddCommand(ctlAgentStateCmd)
	ctlAgentCmd.AddCommand(ctlAgentWatchCmd)
	ctlAgentCmd.AddCommand(ctlAgentPromptCmd)
	ctlAgentCmd.AddCommand(ctlAgentWaitCmd)
	ctlSessionCmd.AddCommand(ctlSessionCaptureCmd)
	ctlCmd.AddCommand(ctlAgentCmd)
	ctlCmd.AddCommand(ctlSessionCmd)
	rootCmd.AddCommand(ctlCmd)
	rootCmd.AddCommand(helpAllCmd)
	rootCmd.AddCommand(versionCmd)
}
